# Background transparency (0.8)
background_opacity 0.9

# Cursor blinking & style
cursor_shape                block
cursor_blink_interval       0.5
cursor_stop_blinking_after  0

# Disable remembering previous size so default size takes priority
remember_window_size  no

# Set initial dimensions (175 columns x 45 lines)
initial_window_width  175c
initial_window_height 45c
